### ISSUE TITLE
One Question on Transformation Matrix of Camera to Floor

### ISSUE THREAD

**Issue by LT-ZHONG** [aperezyus/stairs_detection#1]
### This stairs-detection project is really interesting and amazing. 
I found a question when I read the source code.  I don't understand the calculation of the transformation matrix from camera coordinates to floor coordinates, which is correspond to the function "_computeCamera2FloorMatrix_" in the source code.
It is confusing that the matrix is totally derived from the floor normal.
Any instruction would be of great help, thanks.

`void GlobalScene::computeCamera2FloorMatrix (Eigen::Vector4f floor_normal) 
{
    // Transformation from Camera to Floor reference frame (c2f) is computed knowing one of the axis (the floor normal, corresponding to Y in our convention)
    Eigen::Matrix3f R;
    Eigen::Vector3f t = Eigen::Vector3f::Zero();

    float a,b,c,d;
    c = sqrt(1/(1+floor_normal(2)*floor_normal(2)/(floor_normal(1)*floor_normal(1))));
    d = -c*floor_normal(2)/floor_normal(1);
    b = 1/(floor_normal(0)+(c*floor_normal(1)*(c*floor_normal(1)-d*floor_normal(2)))/floor_normal(0)-(d*floor_normal(2)*(c*floor_normal(1)-d*floor_normal(2)))/floor_normal(0));
    a = b*(c*floor_normal(1)-d*floor_normal(2))/floor_normal(0);
        
    R << a, -b*c, b*d, b, a*c, -a*d, 0, d, c;
    t(1) = -a*floor_normal(3);

    c2f = ( Eigen::Translation3d (t.cast<double>()) * Eigen::AngleAxisd (R.cast<double>()));
    f2c = c2f.inverse();
    person_height_ = float(fabs(c2f(1,3)));
}`

**Comment by aperezyus** [comment]
Hi!

Thanks for being interested in our work. I'll be glad to help! I wrote this function loong time ago, but hopefully I can guide you through my mental process at the time.

First of all, considering the following axes:
![Screenshot from 2020-05-12 11-10-16](https://user-images.githubusercontent.com/16196743/81665823-80a05e00-9441-11ea-9848-2bfaf53e6a4c.png)

The idea is to transform the coordinate system from Ck to F, knowing the floor vector **v**F. A way to get the rotation part of the transformation is to think about the rotations needed so that the new **y**F is aligned with **v**F. I chose a rotation in **x**Ck to make **z**Ck aligned with the **z**F, and then a rotation along the new **z**F to make the alignment of **y**F with **v**F. 

Although the notation is slightly different, I think this excerpt from my Master's thesis may help you out understanding the code in _computeCamera2FloorMatrix_:
![Screenshot from 2020-05-12 11-03-06](https://user-images.githubusercontent.com/16196743/81667501-a0388600-9443-11ea-9cca-3cf016550532.png)

Notice that _n_ is what was called before **v**F, which is _floor_normal_ in the code, which corresponds to the floor plane equation _Ax + By + Cz + D = 0_. Floats _a_, _b_, _c_ and _d_ are simply the sines and cosines with shamefully non-intuitive variable names.

In retrospect, this function is not very well written and it might not be the most elegant solution, but I  think it should work okay. I hope now at least you can understand what was my idea at that time,  apologize if this made you waste some time trying to figure it out!

Alejandro

**Comment by LT-ZHONG** [comment]
### Hi authors,
Thank you for your patience, I have totally understood the idea due to your well-explained reply. 
I named variables `floats a, b, c, d` like this 
`float cos_gamma, sin_gamma, cos_alpha, sin_alpha`, which I think will be more intuitive.

By the way, on the occasion of COVID-19, hope all of you are safe and sound.
